name: API CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "apps/api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: pwd
        run: pwd
        working-directory: apps/api

      - name: Install dependencies
        run: yarn
        working-directory: apps/api

      - name: list files
        run: ls -la
        working-directory: apps/api

      - name: Run tests
        run: npx nx run api:test:ci --skip-nx-cache
        working-directory: apps/api

      - name: Build API
        run: npx nx run api:build --skip-nx-cache
        working-directory: apps/api
