name: UI CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: yarn install
        working-directory: apps/client

      - name: Run tests
        run: npx nx run ui:test:ci --skip-nx-cache
        working-directory: apps/client

      - name: Build UI
        run: npx nx run ui:build:production --skip-nx-cache
        working-directory: apps/client
