name: UI CD

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "apps/client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: yarn install
        working-directory: apps/client

      - name: Build UI
        run: npx nx run ui:build:production --skip-nx-cache
        working-directory: apps/client

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: apps/client
          push: true
          tags: ghcr.io/jtoniolo/email_sweeperr_client:${{ vars.BRANCH_TAG }}
